version: "3"

networks:
    nocobase:
        driver: bridge

services:
    app:
        image: nocobase/nocobase:latest-full
        restart: always
        networks:
            - nocobase
        depends_on:
            - postgres
        environment:
            # The application's secret key, used to generate user tokens, etc.
            # If APP_KEY is changed, old tokens will also become invalid.
            # It can be any random string, and make sure it is not exposed.
            - APP_KEY=a37b1f42d57d3e6c84ef529b17da2f6bbf4c9a08d2f364ba92fbc06de1a88a3c
            # Database type, supports postgres, mysql, mariadb
            - DB_DIALECT=postgres
            # Database host, can be replaced with the IP of an existing database server
            - DB_HOST=postgres
            # Database port
            - DB_PORT=5432
            # Database name
            - DB_DATABASE=pms
            # Database user
            - DB_USER=pms
            # Database password
            - DB_PASSWORD=Vera7muskQin
            # Timezone
            - TZ=UTC
        volumes:
            - ./storage:/app/nocobase/storage
        ports:
            - "13000:80"
        # init: true

    # If using an existing database server, postgres service can be omitted
    postgres:
        image: postgres:16
        restart: always
        command: postgres -c wal_level=logical
        environment:
            POSTGRES_USER: pms
            POSTGRES_DB: pms
            POSTGRES_PASSWORD: Vera7muskQin
        volumes:
            - ./storage/db/postgres:/var/lib/postgresql/data
        networks:
            - nocobase
